package hxsge.format.json.sjson;

@:enum abstract SJsonBlockType(Int) from Int to Int {
	var SJSON_BT_NULL = 0;
	var SJSON_BT_FALSE = 1;
	var SJSON_BT_TRUE = 2;
	var SJSON_BT_ESTRING = 3;
	var SJSON_BT_UINT8 = 4;
	var SJSON_BT_UINT16 = 5;
	var SJSON_BT_UINT32 = 6;
	var SJSON_BT_UINT64 = 7;
	var SJSON_BT_INT8 = 8;
	var SJSON_BT_INT16 = 9;
	var SJSON_BT_INT32 = 10;
	var SJSON_BT_INT64 = 11;
	var SJSON_BT_FLOAT32 = 12;
	var SJSON_BT_FLOAT64 = 13;
	var SJSON_BT_STRING_UINT8 = 14;
	var SJSON_BT_STRING_UINT16 = 15;
	var SJSON_BT_STRING_UINT32 = 16;
	var SJSON_BT_STRING_UINT64 = 17;
	var SJSON_BT_BINARY_UINT8 = 18;
	var SJSON_BT_BINARY_UINT16 = 19;
	var SJSON_BT_BINARY_UINT32 = 20;
	var SJSON_BT_BINARY_UINT64 = 21;
	var SJSON_BT_ARRAY_UINT8 = 22;
	var SJSON_BT_ARRAY_UINT16 = 23;
	var SJSON_BT_ARRAY_UINT32 = 24;
	var SJSON_BT_ARRAY_UINT64 = 25;
	var SJSON_BT_MAP_UINT8 = 26;
	var SJSON_BT_MAP_UINT16 = 27;
	var SJSON_BT_MAP_UINT32 = 28;
	var SJSON_BT_MAP_UINT64 = 29;
}
